<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>PSA.DataAccess</RootNamespace>
		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="bin\**\*.cs;obj\**\*.cs" />
		<Compile Include="DAO\EvaluacionDAO.cs" />
		<Compile Include="DbContextHelper.cs" />
		<Compile Include="DAO\FincaDAO.cs" />
		<Compile Include="DAO\RecuperacionContrasenaDAO.cs" />
		<Compile Include="DAO\TokenRecuperacionDAO.cs" />
		<Compile Include="DAO\UsuarioDAO.cs" />
		<ProjectReference Include="..\PSA.EntidadesDTO\PSA.EntidadesDTO.csproj" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
	</ItemGroup>

</Project>
