name: Deploy PSA API

on:
  push:
    branches:
      - development

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore ./PSA.WebAPI/PSA.WebAPI.csproj

      - name: Build
        run: dotnet build ./PSA.WebAPI/PSA.WebAPI.csproj --configuration Release --no-restore

      - name: Publish API
        run: dotnet publish ./PSA.WebAPI/PSA.WebAPI.csproj -c Release -o ./publish-api

      - name: Show published files
        run: ls -la ./publish-api

      - name: Deploy API
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'psa-api'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
          package: ./publish-api
